### ISSUE TITLE
OpenSSL linking now that Apple doesn't provide it

### ISSUE THREAD

**Issue by slackersoft** [seattle-beach/alfalfa#2]
It took me a while, but I think I've figured out how to everything to work, but I'm not sure how to get ansible to add an environment variable (probably in to bash_it somewhere).

I think we want to add `PKG_CONFIG_PATH` and set it to the `lib/pkgconfig` dir under whichever openssl has just been installed.

Probably something like

``` bash
PKG_CONFIG_PATH=/usr/local/Cellar/openssl/$(ls /usr/local/Cellar/openssl/ | tail -1)/lib/pkgconfig
```

**Comment by kejadlen** [comment]
Fixed by https://github.com/seattle-beach/bash-it/commit/7d127665eb7fff1b460e1900ec138a1bba02d3c8
