### ISSUE TITLE
Install ShiftIt as part of main playbook

### ISSUE THREAD

**Issue by ghost** [seattle-beach/alfalfa#7]
The main playbook fails if ShiftIt isn't already installed. Why not do `brew cask install shiftit` as part of the main playbook?

**Comment by kejadlen** [comment]
Used to, but the default Pivotal image should include ShiftIt by default. It /should/ do no harm to include it in the [Brewfile](https://github.com/seattle-beach/alfalfa/blob/master/Brewfile).

**Comment by kejadlen** [comment]
Fixed in the latest commit - not sure why GitHub didn't link and auto-close this issue...
